# Generated by Django 4.2.7 on 2023-12-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='failed_login_num',
            field=models.IntegerField(default=0),
        ),
    ]
