# Generated by Django 4.2.7 on 2023-12-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_datetime',
        ),
    ]
