# Generated by Django 4.2.7 on 2024-01-11 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_userinfo_is_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/', validators=[home.models.validate_file_type_and_size])),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('category_enum', models.IntegerField(choices=[(1, 'SOCIAL'), (2, 'EDUCATIONAL'), (3, 'PROGRAMMING'), (4, 'NETWORKING')])),
                ('show', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
